### PR TITLE
using existing NSData base64 encoding methods(iOS7+)

### PR DESCRIPTION
**Pull request by justhappens**
Code from Cordova-sqlite-storage

### CODE REVIEW

**Comment by mvila** [comment]
Thanks @justhappens for this improvement but as you know the native part of this plugin comes from [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) and since I am not very confortable developing in Objective-C (here I coded only the JavaScript wrapper), I cannot confidently validate your pull request. So, I think the best is I take the all code from [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage/tree/storage-master/src/ios).

**Comment by justhappens** [comment]
Thanks for your reply. The updated native code is actually from the latest version of cordova-sqlite-storage

**Comment by mvila** [comment]
OK I will update this repository with the last version of cordova-sqlite-storage. But since I have some apps in production, I need to make some tests and it could take awhile... Just for curiosity, are you using my plugin in production? If you do, why do you use it instead of the original cordova-sqlite-storage?

**Comment by mvila** [comment]
I updated the iOS code from cordova-sqlite-storage. So now the base64 encoding shouldn't be an issue anymore.

**Pull request closed without merging**
